services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --timeout 120 --workers 2 --bind 0.0.0.0:10000
    envVars:
      - key: FLASK_ENV
        value: production
